FROM ubuntu:20.04

MAINTAINER tiktikimelbo7 tiktikimelbo7@gmail.com

ENV DEBIAN_FRONTEND="noninteractive

RUN apt update && upgrade
RUN apt install libcurl-devel libcurl4-openssl-dev
RUN apt install c-ares-devel libcares-devel libc-ares-dev
RUN apt install openssl-devel libssl-dev
RUN apt install libcryptopp-devel libcrypto++-dev
